name: Chore
description: Chore request
type: 'Chore 🧹'
title: '[Chore]: '
labels: ["chore", "needs-triage"]
body:
  - type: textarea
    id: description
    attributes:
      label: Description
      description: Describe the need. Why is it needed? What is the expected outcome? What is the impact?
      placeholder: Describe the task
    validations:
      required: true

  - type: textarea
    id: additional-context
    attributes:
      label: "Additional Context"
      description: "Add any other context or details about the problem here (e.g. link to Discussion, etc.)."
    required: false
