name: Release Please
permissions: write-all
on:
  workflow_call:
    secrets:
      GH_PAT_RELEASE_PLEASE:
        required: true
jobs:
  release-please:
    name: Release Please
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - uses: googleapis/release-please-action@d1a8f221d7723166f48a584aebba00ef3f6febec # v4
        id: release
        with:
          token: ${{ secrets.GH_PAT_RELEASE_PLEASE }}
          release-type: node
