name: Release Please
permissions: write-all
on:
  workflow_call:
    secrets:
      GH_PAT_RELEASE_PLEASE:
        required: true
jobs:
  release-please:
    name: Release Please
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - uses: googleapis/release-please-action@7987652d64b4581673a76e33ad5e98e3dd56832f # v4
        id: release
        with:
          token: ${{ secrets.GH_PAT_RELEASE_PLEASE }}
          release-type: node
