name: On Merge to main
on:
  push:
    branches:
      - main
      - chore/release-please
permissions:
    contents: write   
jobs:
  security:
    name: Security Checks
    uses: ./.github/workflows/_security-checks.yml

  static-checks:
    name: Static Checks
    uses: ./.github/workflows/_static-checks.yml
    secrets: inherit

  unit-tests:
    name: Unit Tests
    uses: ./.github/workflows/_unit-tests.yml
    secrets: inherit

  release-please:
    name: Release Please
    uses: ./.github/workflows/_release-please.yml
    secrets:
      GH_PAT_RELEASE_PLEASE: ${{ secrets.GITHUB_TOKEN }} # Note: This won't allow running workflows on the PR, we'll need to check in a PAT issued by StacklokBot
